spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews_db
    username: postgres
    password: 4137
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect